### ISSUE TITLE
How can I render image by webGl

### ISSUE THREAD

**Issue by xiaoshidetaikuai** [rasmuse/d3-geo-warp#1]
hi, I try your js to render earthImg, but when the screen is large,drag the earth was very slowly,I want render earth by webGL,like pixi.js or three,js, how can I change it simpely.?

**Comment by rasmuse** [comment]
No wonder it is slow! The implementation was meant as proof-of-concept and not for production.

It's not obvious how to do this using WebGL, since the geographical transformations cannot (I guess) be run on the GPU without essentially re-implementing everything.

Now I'm just speculating, but one possible approximate solution could be to calculate the geographical transform on a coarse grid (without WebGL) and then use a WebGL shader to interpolate. But clearly this is outside the current scope of this little demo project.

Closing this issue for now, but please let me know if you make a WebGL implementation. That would be very cool and useful.
